### ISSUE TITLE
Notification Count - Color

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/oms#14]
- Change notification color from dark color to light colour

**Comment by cjzamora** [comment]
Done. Please refer to 3404539db1c2dcc50cc773f45000b663af3c0190

**Comment by JosephFidelino** [comment]
Tested. Background color is `#ABBAC3`

![screen shot 2018-03-08 at 12 43 25 pm](https://user-images.githubusercontent.com/26085313/37133440-5be4c6d2-22ce-11e8-85cd-b6ae6debb9af.png)
