### ISSUE TITLE
BUG: Can login even if password is wrong.

### ISSUE THREAD

**Issue by cjzamora** [CradlePHP/oms#24]

**Comment by cjzamora** [comment]
I was able to login even if the password is not right.

**Comment by cjzamora** [comment]
For reference 49299befc52af99457821b9366ae23d3807fa2f2

**Comment by JosephFidelino** [comment]
Tested. Good to close.

![screen shot 2018-03-08 at 2 33 22 pm](https://user-images.githubusercontent.com/26085313/37136714-b902f668-22dd-11e8-94b1-0cfdd484991d.png)
