### ISSUE TITLE
Count per Menu Item

### ISSUE THREAD

**Issue by cblanquera** [CradlePHP/oms#3]
Do a call to get all the table counts
https://stackoverflow.com/questions/286039/get-record-counts-for-all-tables-in-mysql-database

Loop through every menu item
If menu item == `/admin/system/object/:name/search` add the count to the menu item

Something like that

**Comment by cjzamora** [comment]
Please refer to 1c46ca3221e3721a5da77155a39e1aa259f5687b

**Comment by cblanquera** [comment]
I validated the code nice work!
