### ISSUE TITLE
Utility - Updates

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/oms#6]
Utility - make it part of the system
   - There will be no Utility Module folder

**Comment by cjzamora** [comment]
Done. Please refer to 1d4aad7fff16419165b4f865928096367008d589 and ae3becbf95c5f0c764de64870cbd3bb800ec34cc.

**Comment by cblanquera** [comment]
https://github.com/CradlePHP/oms/commit/23c09a4ec2b150a996e69548d29f7bfb1bd50404

changed the rest.
